qf_agent_version: "{{ lookup('file', playbook_dir + '/../../version/version.go') | regex_search('Version = \"([^\"]+)\"', '\\1') | first }}"

qf_agent_deb_url: "https://github.com/qzmi4meister/qf/releases/download/v{{ qf_agent_version }}/qf-agent_{{ qf_agent_version }}_amd64.deb"
qf_agent_rpm_url: "https://github.com/qzmi4meister/qf/releases/download/v{{ qf_agent_version }}/qf-agent-{{ qf_agent_version }}.x86_64.rpm"

qf_agent_deb_dest: "/tmp/qf-agent_{{ qf_agent_version }}_amd64.deb"
qf_agent_rpm_dest: "/tmp/qf-agent-{{ qf_agent_version }}.x86_64.rpm"
