apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qf-cp.fullname" . }}-secrets
  labels:
    {{- include "qf-cp.labels" . | nindent 4 }}
type: Opaque
stringData:
  QF_DB_DSN: {{ .Values.secrets.dbDSN | quote }}
  QF_MASTER_KEY: {{ .Values.secrets.masterKey | quote }}
  {{- if .Values.secrets.jwtSecret }}
  QF_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  QF_ADMIN_EMAIL: {{ .Values.secrets.adminEmail | quote }}
  QF_ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  {{- if .Values.secrets.oidcClientSecret }}
  QF_OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
  {{- end }}
