// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type TcFilterCtEntry struct {
	LastSeenNs    uint64
	EstablishedNs uint64
	PacketsFwd    uint64
	BytesFwd      uint64
	PacketsRev    uint64
	BytesRev      uint64
	State         uint8
	TcpState      uint8
	Pad           [6]uint8
}

type TcFilterCtKey struct {
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	Pad     [3]uint8
}

type TcFilterIpsetLpmKey struct {
	Prefixlen uint32
	IpsetId   uint32
	Addr      uint32
}

type TcFilterRuleCounter struct {
	Packets uint64
	Bytes   uint64
}

type TcFilterRuleEntry struct {
	Action             uint8
	LogEnabled         uint8
	LogRateLimitPerSec uint16
	Pad                uint32
	RuleIdHi           uint64
	RuleIdLo           uint64
	Match              struct {
		Protocol   uint8
		Direction  uint8
		N_srcCidrs uint8
		N_dstCidrs uint8
		N_srcPorts uint8
		N_dstPorts uint8
		State      uint8
		Pad        uint8
		SrcCidrs   [8]struct {
			Addr uint32
			Mask uint32
		}
		DstCidrs [8]struct {
			Addr uint32
			Mask uint32
		}
		SrcPorts [8]struct {
			Start uint16
			End   uint16
		}
		DstPorts [8]struct {
			Start uint16
			End   uint16
		}
		SrcIpsetId uint32
		DstIpsetId uint32
	}
}

// LoadTcFilter returns the embedded CollectionSpec for TcFilter.
func LoadTcFilter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcFilterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcFilter: %w", err)
	}

	return spec, err
}

// LoadTcFilterObjects loads TcFilter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcFilterObjects
//	*TcFilterPrograms
//	*TcFilterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcFilterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcFilter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcFilterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcFilterSpecs struct {
	TcFilterProgramSpecs
	TcFilterMapSpecs
	TcFilterVariableSpecs
}

// TcFilterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcFilterProgramSpecs struct {
	QfTcEgress  *ebpf.ProgramSpec `ebpf:"qf_tc_egress"`
	QfTcIngress *ebpf.ProgramSpec `ebpf:"qf_tc_ingress"`
}

// TcFilterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcFilterMapSpecs struct {
	QfConfig       *ebpf.MapSpec `ebpf:"qf_config"`
	QfConntrack    *ebpf.MapSpec `ebpf:"qf_conntrack"`
	QfEvents       *ebpf.MapSpec `ebpf:"qf_events"`
	QfIpsets       *ebpf.MapSpec `ebpf:"qf_ipsets"`
	QfRuleCount    *ebpf.MapSpec `ebpf:"qf_rule_count"`
	QfRuleCounters *ebpf.MapSpec `ebpf:"qf_rule_counters"`
	QfRules        *ebpf.MapSpec `ebpf:"qf_rules"`
}

// TcFilterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcFilterVariableSpecs struct {
}

// TcFilterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcFilterObjects struct {
	TcFilterPrograms
	TcFilterMaps
	TcFilterVariables
}

func (o *TcFilterObjects) Close() error {
	return _TcFilterClose(
		&o.TcFilterPrograms,
		&o.TcFilterMaps,
	)
}

// TcFilterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcFilterMaps struct {
	QfConfig       *ebpf.Map `ebpf:"qf_config"`
	QfConntrack    *ebpf.Map `ebpf:"qf_conntrack"`
	QfEvents       *ebpf.Map `ebpf:"qf_events"`
	QfIpsets       *ebpf.Map `ebpf:"qf_ipsets"`
	QfRuleCount    *ebpf.Map `ebpf:"qf_rule_count"`
	QfRuleCounters *ebpf.Map `ebpf:"qf_rule_counters"`
	QfRules        *ebpf.Map `ebpf:"qf_rules"`
}

func (m *TcFilterMaps) Close() error {
	return _TcFilterClose(
		m.QfConfig,
		m.QfConntrack,
		m.QfEvents,
		m.QfIpsets,
		m.QfRuleCount,
		m.QfRuleCounters,
		m.QfRules,
	)
}

// TcFilterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcFilterVariables struct {
}

// TcFilterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcFilterPrograms struct {
	QfTcEgress  *ebpf.Program `ebpf:"qf_tc_egress"`
	QfTcIngress *ebpf.Program `ebpf:"qf_tc_ingress"`
}

func (p *TcFilterPrograms) Close() error {
	return _TcFilterClose(
		p.QfTcEgress,
		p.QfTcIngress,
	)
}

func _TcFilterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcfilter_bpfeb.o
var _TcFilterBytes []byte
