// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type TcFilterCompatCtEntry struct {
	LastSeenNs    uint64
	EstablishedNs uint64
	PacketsFwd    uint64
	BytesFwd      uint64
	PacketsRev    uint64
	BytesRev      uint64
	State         uint8
	TcpState      uint8
	Pad           [6]uint8
}

type TcFilterCompatCtKey struct {
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	Pad     [3]uint8
}

type TcFilterCompatIpsetLpmKey struct {
	Prefixlen uint32
	IpsetId   uint32
	Addr      uint32
}

type TcFilterCompatQfTokenBucket struct {
	LastNs uint64
	Tokens uint32
	Pad    uint32
}

type TcFilterCompatRuleCounter struct {
	Packets uint64
	Bytes   uint64
}

type TcFilterCompatRuleEntry struct {
	Action             uint8
	LogEnabled         uint8
	LogRateLimitPerSec uint16
	Pad                uint32
	RuleIdHi           uint64
	RuleIdLo           uint64
	Match              struct {
		Protocol   uint8
		Direction  uint8
		N_srcCidrs uint8
		N_dstCidrs uint8
		N_srcPorts uint8
		N_dstPorts uint8
		State      uint8
		Pad        uint8
		SrcCidrs   [8]struct {
			Addr uint32
			Mask uint32
		}
		DstCidrs [8]struct {
			Addr uint32
			Mask uint32
		}
		SrcPorts [8]struct {
			Start uint16
			End   uint16
		}
		DstPorts [8]struct {
			Start uint16
			End   uint16
		}
		SrcIpsetId uint32
		DstIpsetId uint32
	}
}

// LoadTcFilterCompat returns the embedded CollectionSpec for TcFilterCompat.
func LoadTcFilterCompat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcFilterCompatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcFilterCompat: %w", err)
	}

	return spec, err
}

// LoadTcFilterCompatObjects loads TcFilterCompat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcFilterCompatObjects
//	*TcFilterCompatPrograms
//	*TcFilterCompatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcFilterCompatObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcFilterCompat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcFilterCompatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcFilterCompatSpecs struct {
	TcFilterCompatProgramSpecs
	TcFilterCompatMapSpecs
	TcFilterCompatVariableSpecs
}

// TcFilterCompatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcFilterCompatProgramSpecs struct {
	QfTcEgress  *ebpf.ProgramSpec `ebpf:"qf_tc_egress"`
	QfTcIngress *ebpf.ProgramSpec `ebpf:"qf_tc_ingress"`
}

// TcFilterCompatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcFilterCompatMapSpecs struct {
	QfConfig          *ebpf.MapSpec `ebpf:"qf_config"`
	QfConntrack       *ebpf.MapSpec `ebpf:"qf_conntrack"`
	QfEvents          *ebpf.MapSpec `ebpf:"qf_events"`
	QfIpsets          *ebpf.MapSpec `ebpf:"qf_ipsets"`
	QfRateLimits      *ebpf.MapSpec `ebpf:"qf_rate_limits"`
	QfRuleCount       *ebpf.MapSpec `ebpf:"qf_rule_count"`
	QfRuleCounters    *ebpf.MapSpec `ebpf:"qf_rule_counters"`
	QfRules           *ebpf.MapSpec `ebpf:"qf_rules"`
	QfSuppressedCount *ebpf.MapSpec `ebpf:"qf_suppressed_count"`
}

// TcFilterCompatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcFilterCompatVariableSpecs struct {
}

// TcFilterCompatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcFilterCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcFilterCompatObjects struct {
	TcFilterCompatPrograms
	TcFilterCompatMaps
	TcFilterCompatVariables
}

func (o *TcFilterCompatObjects) Close() error {
	return _TcFilterCompatClose(
		&o.TcFilterCompatPrograms,
		&o.TcFilterCompatMaps,
	)
}

// TcFilterCompatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcFilterCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcFilterCompatMaps struct {
	QfConfig          *ebpf.Map `ebpf:"qf_config"`
	QfConntrack       *ebpf.Map `ebpf:"qf_conntrack"`
	QfEvents          *ebpf.Map `ebpf:"qf_events"`
	QfIpsets          *ebpf.Map `ebpf:"qf_ipsets"`
	QfRateLimits      *ebpf.Map `ebpf:"qf_rate_limits"`
	QfRuleCount       *ebpf.Map `ebpf:"qf_rule_count"`
	QfRuleCounters    *ebpf.Map `ebpf:"qf_rule_counters"`
	QfRules           *ebpf.Map `ebpf:"qf_rules"`
	QfSuppressedCount *ebpf.Map `ebpf:"qf_suppressed_count"`
}

func (m *TcFilterCompatMaps) Close() error {
	return _TcFilterCompatClose(
		m.QfConfig,
		m.QfConntrack,
		m.QfEvents,
		m.QfIpsets,
		m.QfRateLimits,
		m.QfRuleCount,
		m.QfRuleCounters,
		m.QfRules,
		m.QfSuppressedCount,
	)
}

// TcFilterCompatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcFilterCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcFilterCompatVariables struct {
}

// TcFilterCompatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcFilterCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcFilterCompatPrograms struct {
	QfTcEgress  *ebpf.Program `ebpf:"qf_tc_egress"`
	QfTcIngress *ebpf.Program `ebpf:"qf_tc_ingress"`
}

func (p *TcFilterCompatPrograms) Close() error {
	return _TcFilterCompatClose(
		p.QfTcEgress,
		p.QfTcIngress,
	)
}

func _TcFilterCompatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcfiltercompat_bpfeb.o
var _TcFilterCompatBytes []byte
